#pipelines:
#  default:
#  - step:
#      name: Build
#      image: maven:3.3.9
#      script:
#      - mvn clean install -DskipTests=true
#  - step:
#      name: Deploy
#      image: python:3.5.1
#      script:
#      - apt-get update
#      - apt-get install -y zip
#      - pip install boto3==1.3.0
#      - zip -r /tmp/artifact.zip target/*.war appspec.yml scripts/*
#      - python codedeploy_deploy.py